name: Python testing workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      tox-env:
        required: true
        type: string

jobs:
  python-tests:
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y libopenjp2-7 graphviz
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-pypi-filter
    - name: Run job
      run: |
        tox -e ${{ inputs.tox-env }}
    - name: Upload test coverage to Codecov
      uses: codecov/codecov-action@v2
